### ISSUE TITLE
Is there original factory lid certificate?

### ISSUE THREAD

**Issue by tin-** [marcoreps/resistors#1]
Thanks for photos. Can I add them into database?

It would be a sad story if factory certificate is not included and replaced only with new 2006 one. 
Also 2006 certificate is a bit lackluster without temperature sensor output value. I like to use that reading to ensure that my measurement on SR104 can replicate temperature of the unit exactly as in calibration lab. ;)

**Comment by marcoreps** [comment]
Absolutely, feel free to add to your databasse!

I'm afraid that's exactly what happened, they must have discarded the original sheet and replaced it with their own :( Do you think there might be a chance to recover anything by contacting ESI or some descendant of that company?
